package cli.shady.terminal

import cli.shady.commands.AliasEntry
import cli.shady.commands.config.ShadyConfig

class ZshIntegrationScript(
    private val config: ShadyConfig,
    private val aliases: List<AliasEntry>,
    private val eventChannelEnabled: Boolean = true,
) {
    fun render(): String = buildString {
        appendLine("# Generated by Shady. Changes are discarded when the session closes.")
        appendLine("if [[ -r \"${'$'}SHADY_ORIGINAL_ZDOTDIR/.zshrc\" ]]; then")
        appendLine("  source \"${'$'}SHADY_ORIGINAL_ZDOTDIR/.zshrc\"")
        appendLine("fi")
        if (eventChannelEnabled) {
            appendLine("exec 9>\"${'$'}SHADY_EVENT_FIFO\"")
        }
        appendLine("export TERM=xterm-256color")
        if (config.terminal.coloredOutput) {
            appendLine("export COLORTERM=truecolor")
            appendLine("export CLICOLOR=1")
            appendLine("unset NO_COLOR")
        } else {
            appendLine("export NO_COLOR=1")
            appendLine("unset COLORTERM CLICOLOR")
        }
        appendLine()
        appendLine("_shady_emit() {")
        if (eventChannelEnabled) {
            appendLine("  builtin printf '%s\\0%s\\0' \"${'$'}1\" \"${'$'}2\" >&9")
        } else {
            appendLine("  :")
        }
        appendLine("}")
        appendLine("typeset -g SHADY_LAST_COMMAND=''")
        appendLine("_shady_preexec() {")
        appendLine("  SHADY_LAST_COMMAND=\"${'$'}1\"")
        appendLine("  _shady_emit COMMAND_STARTED \"${'$'}1\"")
        appendLine("}")
        appendLine("_shady_precmd() {")
        appendLine("  local command_status=${'$'}?")
        appendLine("  if [[ -n \"${'$'}SHADY_LAST_COMMAND\" ]]; then")
        appendLine("    _shady_emit COMMAND_FINISHED \"${'$'}command_status\"")
        appendLine("    SHADY_LAST_COMMAND=''")
        appendLine("  fi")
        appendLine("  builtin printf '\\e[1 q'")
        appendLine("  _shady_emit PROMPT_READY \"${'$'}PWD\"")
        appendLine("}")
        appendLine("preexec_functions=(_shady_preexec ${'$'}preexec_functions)")
        appendLine("precmd_functions=(_shady_precmd ${'$'}precmd_functions)")
        appendLine()
        appendLine("shady() {")
        if (eventChannelEnabled) {
            appendLine("  if [[ \"${'$'}1\" == start ]]; then")
            appendLine("    builtin print -u2 -- 'shady: a terminal session is already running'")
            appendLine("    return 2")
            appendLine("  fi")
        }
        appendLine("  command \"${'$'}SHADY_JAVA_BIN\" -cp \"${'$'}SHADY_CLASSPATH\" cli.shady.MainKt \"${'$'}@\"")
        appendLine("}")
        appendLine("gdir() {")
        appendLine("  case \"${'$'}1\" in")
        appendLine("    add|list|remove|help)")
        appendLine("      shady gdir \"${'$'}@\"")
        appendLine("      ;;")
        appendLine("    '')")
        appendLine("      shady gdir")
        appendLine("      ;;")
        appendLine("    *)")
        appendLine("      local target")
        appendLine("      target=\"${'$'}(shady gdir \"${'$'}@\")\" || return ${'$'}?")
        appendLine("      [[ -n \"${'$'}target\" ]] || return 1")
        appendLine("      builtin cd \"${'$'}target\"")
        appendLine("      ;;")
        appendLine("  esac")
        appendLine("}")
        if (eventChannelEnabled) {
            appendLine("sys() { shady sys \"${'$'}@\" }")
            appendLine("dashboard() { shady dashboard \"${'$'}@\" }")
            appendLine("resource() { shady resource \"${'$'}@\" }")
            appendLine("windows() { shady windows \"${'$'}@\" }")
        }
        appendLine("styles() { shady styles \"${'$'}@\" }")
        appendLine("cc() { shady cc \"${'$'}@\" }")
        appendLine("color-commands() { shady color-commands \"${'$'}@\" }")
        appendLine("prehook() { shady prehook \"${'$'}@\" }")
        appendLine()
        appendLine("_shady_accept_line() {")
        appendLine("  local input=\"${'$'}BUFFER\"")
        appendLine("  while [[ \"${'$'}input\" == 'shady shady '* ]]; do")
        appendLine("    input=\"${'$'}{input#shady }\"")
        appendLine("  done")
        appendLine("  if [[ \"${'$'}input\" == 'shady '* ]]; then")
        appendLine("    local without_prefix=\"${'$'}{input#shady }\"")
        appendLine("    local first=\"${'$'}{without_prefix%% *}\"")
        appendLine("    case \"${'$'}first\" in")
        appendLine("      start|help|alias|gdir|prehook|sys|system|resource|resources|monitor|dashboard|windows|window|wins|styles|cc|color-commands|config|update) BUFFER=\"shady ${'$'}without_prefix\" ;;")
        appendLine("      *) BUFFER=\"${'$'}without_prefix\" ;;")
        appendLine("    esac")
        appendLine("  elif [[ \"${'$'}input\" == alias\\ * ]]; then")
        appendLine("    local alias_action=\"${'$'}{${'$'}{input#alias }%% *}\"")
        appendLine("    case \"${'$'}alias_action\" in")
        appendLine("      add|list|suggest|accept) BUFFER=\"shady ${'$'}input\" ;;")
        appendLine("    esac")
        appendLine("  fi")
        appendLine("  zle .accept-line")
        appendLine("}")
        appendLine("zle -N accept-line _shady_accept_line")
        appendLine()
        appendLine("autoload -Uz compinit")
        appendLine("if (( ! ${'$'}+functions[compdef] )); then compinit -i; fi")
        appendLine("_shady() {")
        appendLine("  local -a commands config_keys colors")
        appendLine("  commands=(start help sys dashboard resource windows styles cc color-commands config alias gdir prehook update)")
        appendLine("  config_keys=(security.alwaysRequestSudo terminal.coloredOutput terminal.usernameOverrideEnabled terminal.username terminal.restoreTabs features.stylesCommandEnabled features.fuzzySearchEnabled features.startupUpdateCheckEnabled updates.repositoryUrl updates.checkIntervalHours)")
        appendLine("  colors=(black red green yellow blue magenta cyan white bright-black bright-red bright-green bright-yellow bright-blue bright-magenta bright-cyan bright-white)")
        appendLine("  if (( CURRENT == 2 )); then")
        appendLine("    _describe 'shady command' commands")
        appendLine("    return")
        appendLine("  fi")
        appendLine("  case \"${'$'}words[2]\" in")
        appendLine("    alias)")
        appendLine("      if (( CURRENT == 3 )); then _values 'alias action' add list suggest accept; else _arguments '*:argument:_files'; fi ;;")
        appendLine("    gdir)")
        appendLine("      if (( CURRENT == 3 )); then _values 'gdir action' add list remove help; else _arguments '*:argument:_files'; fi ;;")
        appendLine("    prehook)")
        appendLine("      if (( CURRENT == 3 )); then _values 'prehook action' add list run; else _arguments '*:argument:_files'; fi ;;")
        appendLine("    config)")
        appendLine("      if (( CURRENT == 3 )); then _values 'config action' show set")
        appendLine("      elif (( CURRENT == 4 )); then _describe 'config key' config_keys")
        appendLine("      elif [[ \"${'$'}words[4]\" == *.Enabled || \"${'$'}words[4]\" == security.alwaysRequestSudo || \"${'$'}words[4]\" == terminal.coloredOutput || \"${'$'}words[4]\" == terminal.restoreTabs ]]; then _values 'boolean' true false")
        appendLine("      fi ;;")
        appendLine("    cc|color-commands)")
        appendLine("      if (( CURRENT == 3 )); then _values 'color action' list command filetype remove reset")
        appendLine("      elif (( CURRENT == 5 )); then _describe 'color' colors")
        appendLine("      fi ;;")
        appendLine("    *) _arguments '*:argument:_files' ;;")
        appendLine("  esac")
        appendLine("}")
        appendLine("compdef _shady shady")
        appendLine("_shady_cc() { local -a colors; colors=(black red green yellow blue magenta cyan white bright-black bright-red bright-green bright-yellow bright-blue bright-magenta bright-cyan bright-white); if (( CURRENT == 2 )); then _values 'color action' list command filetype remove reset; elif (( CURRENT == 4 )); then _describe 'color' colors; fi }")
        appendLine("_shady_prehook() { if (( CURRENT == 2 )); then _values 'prehook action' add list run; else _arguments '*:argument:_files'; fi }")
        appendLine("_shady_gdir() { if (( CURRENT == 2 )); then _values 'gdir action' add list remove help; else _arguments '*:argument:_files'; fi }")
        appendLine("compdef _shady_cc cc color-commands")
        appendLine("compdef _shady_prehook prehook")
        appendLine("compdef _shady_gdir gdir")
        appendLine("compdef _shady styles sys dashboard resource windows")
        appendLine()
        aliases.forEach { alias ->
            appendLine("alias ${alias.name}=${alias.command.shellQuote()}")
        }
        appendLine()
        val username = config.terminal.username.takeIf(String::isNotBlank) ?: "user"
        val prompt = if (config.terminal.usernameOverrideEnabled) {
            "%F{10}${username}@%~ %#%f "
        } else {
            "%F{10}%n@%~ %#%f "
        }
        appendLine("PROMPT=${prompt.shellQuote()}")
    }

    private fun String.shellQuote(): String = "'${replace("'", "'\\''")}'"
}
